apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{.Replica}}-{{.Iteration}}
spec:
  podSelector:
    matchLabels:
      app: ubi9
      replica: {{.Replica}}
      iteration: {{.Iteration}}
  ingress:
  - ports:
    - protocol: TCP
      port: 8000
