apiVersion: v1
kind: Service
metadata:
  name: ubi9-{{.Replica}}-{{.Iteration}}
spec:
  selector:
    matchLabels:
      app: ubi9
      replica: {{.Replica}}
      iteration: {{.Iteration}}
  ports:
    - protocol: TCP
      name: 8000
      port: 8000
